driver_key_val_pair = {'RIC': '3',
                       'NOR': '4',
                       'BOT': '77',
                       'LEC': '16',
                       'PER': '11',
                       'SAI': '55',
                       'STR': '18',
                       'ALO': '14',
                       'RUS': '63',
                       'OCO': '31',
                       'LAT': '6',
                       'VET': '5',
                       'GIO': '99',
                       'KUB': '88',
                       'MSC': '47',
                       'MAZ': '9',
                       'HAM': '44',
                       'VER': '33',
                       'GAS': '10',
                       'TSU': '22'}

team_color_pair = {'Red Bull Racing': '#0600ef',
                   'Williams': '#ADD8E6',
                   'Mercedes': '#00D2BE',
                   'AlphaTauri': '#3e454d',
                   'Alpine': '#0090ff',
                   'Ferrari': '#dc0000',
                   'Alpha Romeo': '#900000',
                   'Haas F1 Team': '#ffffff',
                   'McLaren': '#ffa112',
                   'Aston Martin': '#006f62',
                   }

# Football
# League Name Changes
image_d = {
    'Barclays Premier League': 'Premier League',
    'German Bundesliga': 'Bundesliga 1',
    'Spanish Primera Division': 'La Liga',
    'French Ligue 1': 'Ligue 1',
    'Dutch Eredivisie': 'Eredivisie',
    'Austrian T-Mobile Bundesliga': 'Tipp3 Bundesliga',
    'Italy Serie A': 'Serie A',
    'Portuguese Liga': 'Primeira Liga',
    'Scottish Premiership': 'Premiership',
    'Brasileiro Série A': 'Brasileiro de Aspirantes',
    'United Soccer League': 'USL Championship',
}
