driver_key_val_pair = {'RIC': '3',
                       'NOR': '4',
                       'BOT': '77',
                       'LEC': '16',
                       'PER': '11',
                       'SAI': '55',
                       'STR': '18',
                       'ALO': '14',
                       'RUS': '63',
                       'OCO': '31',
                       'LAT': '6',
                       'VET': '5',
                       'GIO': '99',
                       'KUB': '88',
                       'MSC': '47',
                       'MAZ': '9',
                       'HAM': '44',
                       'VER': '33',
                       'GAS': '10',
                       'TSU': '22'}

team_color_pair = {'Red Bull Racing': '#0600ef',
                   'Williams': '#ADD8E6',
                   'Mercedes': '#00D2BE',
                   'AlphaTauri': '#3e454d',
                   'Alpine': '#0090ff',
                   'Ferrari': '#dc0000',
                   'Alpha Romeo': '#900000',
                   'Haas F1 Team': '#ffffff',
                   'McLaren': '#ffa112',
                   'Aston Martin': '#006f62',
                   }

# Football
# League Name Changes
image_d = {
    'Barclays Premier League': 'Premier League',
    'German Bundesliga': 'Bundesliga 1',
    'Spanish Primera Division': 'La Liga',
    'French Ligue 1': 'Ligue 1',
    'Dutch Eredivisie': 'Eredivisie',
    'Austrian T-Mobile Bundesliga': 'Tipp3 Bundesliga',
    'Italy Serie A': 'Serie A',
    'Portuguese Liga': 'Primeira Liga',
    'Scottish Premiership': 'Premiership',
    'Brasileiro Série A': 'Brasileiro de Aspirantes',
    'United Soccer League': 'USL Championship',
}

# League Images
leg = {
    'Barclays Premier League': 'https://media.api-sports.io/football/leagues/39.png',
    'German Bundesliga': 'https://media.api-sports.io/football/leagues/78.png',
    'Spanish Primera Division': 'https://media.api-sports.io/football/leagues/140.png',
    'French Ligue 1': 'https://media.api-sports.io/football/leagues/186.png',
    'Dutch Eredivisie': 'https://media.api-sports.io/football/leagues/88.png',
    'Austrian T-Mobile Bundesliga': 'https://media.api-sports.io/football/leagues/218.png',
    'Italy Serie A': 'https://media.api-sports.io/football/leagues/242.png',
    'Portuguese Liga': 'https://media.api-sports.io/football/leagues/94.png',
    'Scottish Premiership': 'https://media.api-sports.io/football/leagues/179.png',
    'Brasileiro Série A': 'https://media.api-sports.io/football/leagues/741.png',
    'United Soccer League': 'https://media.api-sports.io/football/leagues/255.png',
}

# Team Images

team_dict = {'Manchester United': 'https://media.api-sports.io/football/teams/33.png',
             'Newcastle': 'https://media.api-sports.io/football/teams/34.png',
             'Bournemouth': 'https://media.api-sports.io/football/teams/35.png',
             'Watford': 'https://media.api-sports.io/football/teams/38.png',
             'Wolves': 'https://media.api-sports.io/football/teams/39.png',
             'Liverpool': 'https://media.api-sports.io/football/teams/40.png',
             'Southampton': 'https://media.api-sports.io/football/teams/41.png',
             'Arsenal': 'https://media.api-sports.io/football/teams/42.png',
             'Burnley': 'https://media.api-sports.io/football/teams/44.png',
             'Everton': 'https://media.api-sports.io/football/teams/45.png',
             'Leicester': 'https://media.api-sports.io/football/teams/46.png',
             'Tottenham': 'https://media.api-sports.io/football/teams/47.png',
             'West Ham': 'https://media.api-sports.io/football/teams/48.png',
             'Chelsea': 'https://media.api-sports.io/football/teams/49.png',
             'Manchester City': 'https://media.api-sports.io/football/teams/50.png',
             'Brighton': 'https://media.api-sports.io/football/teams/51.png',
             'Crystal Palace': 'https://media.api-sports.io/football/teams/52.png',
             'Sheffield Utd': 'https://media.api-sports.io/football/teams/62.png',
             'Aston Villa': 'https://media.api-sports.io/football/teams/66.png',
             'Norwich': 'https://media.api-sports.io/football/teams/71.png',
             'Bayern Munich': 'https://media.api-sports.io/football/teams/157.png',
             'Fortuna Dusseldorf': 'https://media.api-sports.io/football/teams/158.png',
             'Hertha Berlin': 'https://media.api-sports.io/football/teams/159.png',
             'SC Freiburg': 'https://media.api-sports.io/football/teams/160.png',
             'VfL Wolfsburg': 'https://media.api-sports.io/football/teams/161.png',
             'Werder Bremen': 'https://media.api-sports.io/football/teams/162.png',
             'Borussia Monchengladbach': 'https://media.api-sports.io/football/teams/163.png',
             'FSV Mainz 05': 'https://media.api-sports.io/football/teams/164.png',
             'Borussia Dortmund': 'https://media.api-sports.io/football/teams/165.png',
             '1899 Hoffenheim': 'https://media.api-sports.io/football/teams/167.png',
             'Bayer Leverkusen': 'https://media.api-sports.io/football/teams/168.png',
             'Eintracht Frankfurt': 'https://media.api-sports.io/football/teams/169.png',
             'FC Augsburg': 'https://media.api-sports.io/football/teams/170.png',
             'RB Leipzig': 'https://media.api-sports.io/football/teams/173.png',
             'FC Schalke 04': 'https://media.api-sports.io/football/teams/174.png',
             'FC Heidenheim': 'https://media.api-sports.io/football/teams/180.png',
             'Union Berlin': 'https://media.api-sports.io/football/teams/182.png',
             'SC Paderborn 07': 'https://media.api-sports.io/football/teams/185.png',
             'FC Koln': 'https://media.api-sports.io/football/teams/192.png',
             'Barcelona': 'https://media.api-sports.io/football/teams/529.png',
             'Atletico Madrid': 'https://media.api-sports.io/football/teams/530.png',
             'Athletic Club': 'https://media.api-sports.io/football/teams/531.png',
             'Valencia': 'https://media.api-sports.io/football/teams/532.png',
             'Villarreal': 'https://media.api-sports.io/football/teams/533.png',
             'Sevilla': 'https://media.api-sports.io/football/teams/536.png',
             'Leganes': 'https://media.api-sports.io/football/teams/537.png',
             'Celta Vigo': 'https://media.api-sports.io/football/teams/538.png',
             'Levante': 'https://media.api-sports.io/football/teams/539.png',
             'Espanyol': 'https://media.api-sports.io/football/teams/540.png',
             'Real Madrid': 'https://media.api-sports.io/football/teams/541.png',
             'Alaves': 'https://media.api-sports.io/football/teams/542.png',
             'Real Betis': 'https://media.api-sports.io/football/teams/543.png',
             'Eibar': 'https://media.api-sports.io/football/teams/545.png',
             'Getafe': 'https://media.api-sports.io/football/teams/546.png',
             'Real Sociedad': 'https://media.api-sports.io/football/teams/548.png',
             'Granada CF': 'https://media.api-sports.io/football/teams/715.png',
             'Valladolid': 'https://media.api-sports.io/football/teams/720.png',
             'Osasuna': 'https://media.api-sports.io/football/teams/727.png',
             'Mallorca': 'https://media.api-sports.io/football/teams/798.png'}
